const Config = {
  "NEXT_PUBLIC_MATIC_RPC_URL": process.env.NEXT_PUBLIC_MATIC_RPC_URL,
  "NEXT_PUBLIC_APP_NAME": process.env.NEXT_PUBLIC_APP_NAME,
  "NEXT_PUBLIC_API_URL": process.env.NEXT_PUBLIC_API_URL,
  "NEXT_PUBLIC_GAME_URL": process.env.NEXT_PUBLIC_GAME_URL,
  "NEXT_PUBLIC_FRONTEND_URL": process.env.NEXT_PUBLIC_FRONTEND_URL,
  "NEXT_PUBLIC_SUPPORT": process.env.NEXT_PUBLIC_SUPPORT,
  "NEXT_PUBLIC_KEYTEXT": process.env.NEXT_PUBLIC_KEYTEXT,
  "NEXT_PUBLIC_MARKETPLACE": process.env.NEXT_PUBLIC_MARKETPLACE,
  "NEXT_PUBLIC_NAKAVERSE": process.env.NEXT_PUBLIC_NAKAVERSE,
  "NEXT_PUBLIC_KEY_RECAPTCHA": process.env.NEXT_PUBLIC_KEY_RECAPTCHA,
  "NEXT_PUBLIC_POLYGON_SCAN": process.env.NEXT_PUBLIC_POLYGON_SCAN,
  "NEXT_PUBLIC_POLYGON_RPC_URL": process.env.NEXT_PUBLIC_POLYGON_RPC_URL,
  "NEXT_PUBLIC_TOKEN_NAME": process.env.NEXT_PUBLIC_TOKEN_NAME,
  "NEXT_PUBLIC_TOKEN_SYMBOL": process.env.NEXT_PUBLIC_TOKEN_SYMBOL,
  "NEXT_PUBLIC_CHAIN_ID": process.env.NEXT_PUBLIC_CHAIN_ID,
  "NEXT_PUBLIC_CHAIN_ID_HEX": process.env.NEXT_PUBLIC_CHAIN_ID_HEX,
  "NEXT_PUBLIC_CHAIN_NAME": process.env.NEXT_PUBLIC_CHAIN_NAME,
  "NEXT_PUBLIC_CONTRACT_ERC20": process.env.NEXT_PUBLIC_CONTRACT_ERC20,
  "NEXT_PUBLIC_OWNER": process.env.NEXT_PUBLIC_OWNER,
  "NEXT_PUBLIC_CONTRACT_BALANCE_VAULT":
    process.env.NEXT_PUBLIC_CONTRACT_BALANCE_VAULT,
  "NEXT_PUBLIC_CONTRACT_ITEM_VAULT":
    process.env.NEXT_PUBLIC_CONTRACT_ITEM_VAULT,
  "NEXT_PUBLIC_CONTRACT_SHOP": process.env.NEXT_PUBLIC_CONTRACT_SHOP,
  "NEXT_PUBLIC_CONTRACT_MARKETPLACE":
    process.env.NEXT_PUBLIC_CONTRACT_MARKETPLACE,
  "NEXT_PUBLIC_CONTRACT_MARKETPLACE_NFT":
    process.env.NEXT_PUBLIC_CONTRACT_MARKETPLACE_NFT,
  "NEXT_PUBLIC_CONTRACT_LAND_NFT": process.env.NEXT_PUBLIC_CONTRACT_LAND_NFT,
  "NEXT_PUBLIC_CONTRACT_GETALLLANDSOFADDRESS":
    process.env.NEXT_PUBLIC_CONTRACT_GETALLLANDSOFADDRESS,
  "NEXT_PUBLIC_CONTRACT_STAKING_30DAY":
    process.env.NEXT_PUBLIC_CONTRACT_STAKING_30DAY,
  "NEXT_PUBLIC_CONTRACT_STAKING_60DAY":
    process.env.NEXT_PUBLIC_CONTRACT_STAKING_60DAY,
  "NEXT_PUBLIC_CONTRACT_STAKING_90DAY":
    process.env.NEXT_PUBLIC_CONTRACT_STAKING_90DAY,
  "NEXT_PUBLIC_CONTRACT_STAKING_A_30DAY":
    process.env.NEXT_PUBLIC_CONTRACT_STAKING_A_30DAY,
  "NEXT_PUBLIC_CONTRACT_STAKING_A_60DAY":
    process.env.NEXT_PUBLIC_CONTRACT_STAKING_A_60DAY,
  "NEXT_PUBLIC_CONTRACT_STAKING_A_90DAY":
    process.env.NEXT_PUBLIC_CONTRACT_STAKING_A_90DAY,
  "NEXT_PUBLIC_CONTRACT_STAKING_FLEXIBLE_180DAY":
    process.env.NEXT_PUBLIC_CONTRACT_STAKING_FLEXIBLE_180DAY,
  "NEXT_PUBLIC_CONTRACT_STAKING_FLEXIBLE_360DAY":
    process.env.NEXT_PUBLIC_CONTRACT_STAKING_FLEXIBLE_360DAY,
  "NEXT_PUBLIC_CONTRACT_BEP20": process.env.NEXT_PUBLIC_CONTRACT_BEP20,
  "NEXT_PUBLIC_CONTRACT_P2P_BINANCE":
    process.env.NEXT_PUBLIC_CONTRACT_P2P_BINANCE,
  "NEXT_PUBLIC_CONTRACT_P2P_POLYGON":
    process.env.NEXT_PUBLIC_CONTRACT_P2P_POLYGON,
  "NEXT_PUBLIC_CONTRACT_ESCAPE_URL": process.env.NEXT_PUBLIC_CONTRACT_ESCAPE_URL
}

export default Config
