#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# git-format-staged -f 'prettier --ignore-unknown --stdin --stdin-filepath "{}"' .

# BY KAEN

echo "🧐 lint staged active..."
yarn lint-staged

# Building Tailwind CSS
yarn build:css ||
(
        echo '🎨🎨🎨 I am building the CSS 🎨🎨🎨'
        false; 
)

# Format code.
echo "🤓 Formating code ... "
yarn format:prettier

# Check Prettier standards  
yarn check:prettier ||
(
    echo '🤢🤮🤢🤮 Its FOKING RAW - Your styling looks disgusting. 🤢🤮🤢🤮
            Prettier Check Failed. Run [yarn format], add changes and try commit again.';
    false;
)
