name: Build on develop
on:
  pull_request:
    types: [opened, reopened, synchronize, edited]
    branches:
      - develop

jobs:
  pr:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2

      - name: Set Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install Dependencies
        run: yarn

      - name: Build
        run: yarn build

      - name: Check lint-staged
        run: yarn lint-staged

      # - name: Check Format
      #   run: yarn format:prettier

      - name: Eslint
        run: yarn check:eslint

      - name: Check Types
        run: yarn check:types

      # - name: Test
      # run: yarn test
